# Based on
# https://github.com/rust-lang/rustfmt/blob/rustfmt-1.4.19/Configurations.md

# Stable
edition = "2018"
fn_args_layout = "Compressed"
max_width = 128
tab_spaces = 4
use_field_init_shorthand = true
use_try_shorthand = true
use_small_heuristics = "Max"

