[package]
name = "common"
version = "0.1.0"
authors = ["James Carl"]
edition = "2018"
license = "AGPL"

[dependencies]
log = "0.4.11"
nalgebra = "0.22.0"
num-traits = "0.2.12"
simba = { version = "0.2.0", features = ["partial_fixed_point_support"] }
legion = "0.3.1"
slotmap = "0.4.0"
rstar = "0.8.2"
lazy_static = "1.4.0"
os_info = "3.0.0"
sys-info = "0.7.0"
memmap = "0.7.0"
threadpool = "1.8.1"
wasmtime = "0.20.0"
ron = "0.6.2"
