[package]
name = "common"
version = "0.1.0"
authors = ["I am the Carl <jamescarl96@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.11"
specs = { version = "0.16.1", features = ["specs-derive"] }
fixed = "1.2.0"
threadpool = "1.8.1"
wasmtime = "0.20.0"
